[versions]
assertj-core = "3.+"
junit-jupiter = "6.+"
snakeyaml-engine = "3.+"
waena = "0.20.0"
spotless = "8.1.0"
testLogger = "4.0.0"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj-core" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-jupiter" }
snakeyaml-engine = { module = "org.snakeyaml:snakeyaml-engine", version.ref = "snakeyaml-engine" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.2.21" }
waenaPublished = { id = "com.github.rahulsom.waena.published", version.ref = "waena" }
waenaRoot = { id = "com.github.rahulsom.waena.root", version.ref = "waena" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
testLogger = { id = "com.adarshr.test-logger", version.ref = "testLogger" }